<?php

/* All Pages Available in this Blog */
$pages_object = get_pages('sort_column=post_parent, menu_order');
$pages_array  = array(
    array(
        'label' => __('Select a Page', TPLNAME), 
        'value' => '',
    )
);
foreach ( $pages_object as $page ) {
    array_push($pages_array, array(
        'label' => $page->post_title,
        'value' => $page->ID,
    ));
}

/* Slider Effects */
$slider_effects = array(
    array('label' => 'blindX', 'value' => 'blindX'),
    array('label' => 'blindY', 'value' => 'blindY'),
    array('label' => 'blindZ', 'value' => 'blindZ'),
    array('label' => 'cover', 'value' => 'cover'),
    array('label' => 'curtainX', 'value' => 'curtainX'),
    array('label' => 'curtainY', 'value' => 'curtainY'),
    array('label' => 'fade', 'value' => 'fade'),
    array('label' => 'fadeZoom', 'value' => 'fadeZoom'),
    array('label' => 'growX', 'value' => 'growX'),
    array('label' => 'growY', 'value' => 'growY'),
    array('label' => 'none', 'value' => 'none'),
    array('label' => 'scrollUp', 'value' => 'scrollUp'),
    array('label' => 'scrollDown', 'value' => 'scrollDown'),
    array('label' => 'scrollLeft', 'value' => 'scrollLeft'),
    array('label' => 'scrollRight', 'value' => 'scrollRight'),
    array('label' => 'fixedScrollHorz', 'value' => 'scrollHorz'),
    array('label' => 'scrollVert', 'value' => 'scrollVert'),
    array('label' => 'shuffle', 'value' => 'shuffle'),
    array('label' => 'slideX', 'value' => 'slideX'),
    array('label' => 'slideY', 'value' => 'slideY'),
    array('label' => 'toss', 'value' => 'toss'),
    array('label' => 'turnUp', 'value' => 'turnUp'),
    array('label' => 'turnDown', 'value' => 'turnDown'),
    array('label' => 'turnLeft', 'value' => 'turnLeft'),
    array('label' => 'turnRight', 'value' => 'turnRight'),
    array('label' => 'uncover', 'value' => 'uncover'),
    array('label' => 'wipe', 'value' => 'wipe'),
    array('label' => 'zoom', 'value' => 'zoom'),
);

/* Slider Speeds */
$slider_speeds = array(
    array('label' => __('Slow', TPLNAME), 'value'=>'900'),
    array('label' => __('Normal', TPLNAME), 'value'=>'600'),
    array('label' => __('Fast', TPLNAME), 'value'=>'300'),
);

/* Google Fonts Options */
$google_fonts = array(
    array('label' => 'Abel','value' => 'Abel'),
    array('label' => 'Abril Fatface','value' => 'Abril+Fatface'),
    array('label' => 'Aclonica','value' => 'Aclonica'),
    array('label' => 'Actor','value' => 'Actor'),
    array('label' => 'Adamina','value' => 'Adamina'),
    array('label' => 'Aguafina Script','value' => 'Aguafina+Script'),
    array('label' => 'Aladin','value' => 'Aladin'),
    array('label' => 'Aldrich','value' => 'Aldrich'),
    array('label' => 'Alice','value' => 'Alice'),
    array('label' => 'Alike Angular','value' => 'Alike+Angular'),
    array('label' => 'Alike','value' => 'Alike'),
    array('label' => 'Allan','value' => 'Allan'),
    array('label' => 'Allerta Stencil','value' => 'Allerta+Stencil'),
    array('label' => 'Allerta','value' => 'Allerta'),
    array('label' => 'Amaranth','value' => 'Amaranth'),
    array('label' => 'Amatic SC','value' => 'Amatic+SC'),
    array('label' => 'Andada','value' => 'Andada'),
    array('label' => 'Andika','value' => 'Andika'),
    array('label' => 'Annie Use Your Telescope','value' => 'Annie+Use+Your+Telescope'),
    array('label' => 'Anonymous Pro','value' => 'Anonymous+Pro'),
    array('label' => 'Antic','value' => 'Antic'),
    array('label' => 'Anton','value' => 'Anton'),
    array('label' => 'Arapey','value' => 'Arapey'),
    array('label' => 'Architects Daughter','value' => 'Architects+Daughter'),
    array('label' => 'Arimo','value' => 'Arimo'),
    array('label' => 'Artifika','value' => 'Artifika'),
    array('label' => 'Arvo','value' => 'Arvo'),
    array('label' => 'Asset','value' => 'Asset'),
    array('label' => 'Astloch','value' => 'Astloch'),
    array('label' => 'Atomic Age','value' => 'Atomic+Age'),
    array('label' => 'Aubrey','value' => 'Aubrey'),
    array('label' => 'Bangers','value' => 'Bangers'),
    array('label' => 'Bentham','value' => 'Bentham'),
    array('label' => 'Bevan','value' => 'Bevan'),
    array('label' => 'Bigshot One','value' => 'Bigshot+One'),
    array('label' => 'Bitter','value' => 'Bitter'),
    array('label' => 'Black Ops One','value' => 'Black+Ops+One'),
    array('label' => 'Bowlby One SC','value' => 'Bowlby+One+SC'),
    array('label' => 'Bowlby One','value' => 'Bowlby+One'),
    array('label' => 'Brawler','value' => 'Brawler'),
    array('label' => 'Bubblegum Sans','value' => 'Bubblegum+Sans'),
    array('label' => 'Buda','value' => 'Buda'),
    array('label' => 'Butcherman Caps','value' => 'Butcherman+Caps'),
    array('label' => 'Cabin Condensed','value' => 'Cabin+Condensed'),
    array('label' => 'Cabin Sketch','value' => 'Cabin+Sketch'),
    array('label' => 'Cabin','value' => 'Cabin'),
    array('label' => 'Cagliostro','value' => 'Cagliostro'),
    array('label' => 'Calligraffitti','value' => 'Calligraffitti'),
    array('label' => 'Candal','value' => 'Candal'),
    array('label' => 'Cantarell','value' => 'Cantarell'),
    array('label' => 'Cardo','value' => 'Cardo'),
    array('label' => 'Carme','value' => 'Carme'),
    array('label' => 'Carter One','value' => 'Carter+One'),
    array('label' => 'Caudex','value' => 'Caudex'),
    array('label' => 'Cedarville Cursive','value' => 'Cedarville+Cursive'),
    array('label' => 'Changa One','value' => 'Changa+One'),
    array('label' => 'Cherry Cream Soda','value' => 'Cherry+Cream+Soda'),
    array('label' => 'Chewy','value' => 'Chewy'),
    array('label' => 'Chicle','value' => 'Chicle'),
    array('label' => 'Chivo','value' => 'Chivo'),
    array('label' => 'Coda Caption','value' => 'Coda+Caption'),
    array('label' => 'Coda','value' => 'Coda'),
    array('label' => 'Comfortaa','value' => 'Comfortaa'),
    array('label' => 'Coming Soon','value' => 'Coming+Soon'),
    array('label' => 'Contrail One','value' => 'Contrail+One'),
    array('label' => 'Convergence','value' => 'Convergence'),
    array('label' => 'Cookie','value' => 'Cookie'),
    array('label' => 'Copse','value' => 'Copse'),
    array('label' => 'Corben','value' => 'Corben'),
    array('label' => 'Cousine','value' => 'Cousine'),
    array('label' => 'Coustard','value' => 'Coustard'),
    array('label' => 'Covered By Your Grace','value' => 'Covered+By+Your+Grace'),
    array('label' => 'Crafty Girls','value' => 'Crafty+Girls'),
    array('label' => 'Creepster Caps','value' => 'Creepster+Caps'),
    array('label' => 'Crimson Text','value' => 'Crimson+Text'),
    array('label' => 'Crushed','value' => 'Crushed'),
    array('label' => 'Cuprum','value' => 'Cuprum'),
    array('label' => 'Damion','value' => 'Damion'),
    array('label' => 'Dancing Script','value' => 'Dancing+Script'),
    array('label' => 'Dawning of a New Day','value' => 'Dawning+of+a+New+Day'),
    array('label' => 'Days One','value' => 'Days+One'),
    array('label' => 'Delius Swash Caps','value' => 'Delius+Swash+Caps'),
    array('label' => 'Delius Unicase','value' => 'Delius+Unicase'),
    array('label' => 'Delius','value' => 'Delius'),
    array('label' => 'Devonshire','value' => 'Devonshire'),
    array('label' => 'Didact Gothic','value' => 'Didact+Gothic'),
    array('label' => 'Dorsa','value' => 'Dorsa'),
    array('label' => 'Dr Sugiyama','value' => 'Dr+Sugiyama'),
    array('label' => 'Droid Sans Mono','value' => 'Droid+Sans+Mono'),
    array('label' => 'Droid Sans','value' => 'Droid+Sans'),
    array('label' => 'Droid Serif','value' => 'Droid+Serif'),
    array('label' => 'EB Garamond','value' => 'EB+Garamond'),
    array('label' => 'Eater Caps','value' => 'Eater+Caps'),
    array('label' => 'Expletus Sans','value' => 'Expletus+Sans'),
    array('label' => 'Fanwood Text','value' => 'Fanwood+Text'),
    array('label' => 'Federant','value' => 'Federant'),
    array('label' => 'Federo','value' => 'Federo'),
    array('label' => 'Fjord One','value' => 'Fjord+One'),
    array('label' => 'Fondamento','value' => 'Fondamento'),
    array('label' => 'Fontdiner Swanky','value' => 'Fontdiner+Swanky'),
    array('label' => 'Forum','value' => 'Forum'),
    array('label' => 'Francois One','value' => 'Francois+One'),
    array('label' => 'Gentium Basic','value' => 'Gentium+Basic'),
    array('label' => 'Gentium Book Basic','value' => 'Gentium+Book+Basic'),
    array('label' => 'Geo','value' => 'Geo'),
    array('label' => 'Geostar Fill','value' => 'Geostar+Fill'),
    array('label' => 'Geostar','value' => 'Geostar'),
    array('label' => 'Give You Glory','value' => 'Give+You+Glory'),
    array('label' => 'Gloria Hallelujah','value' => 'Gloria+Hallelujah'),
    array('label' => 'Goblin One','value' => 'Goblin+One'),
    array('label' => 'Gochi Hand','value' => 'Gochi+Hand'),
    array('label' => 'Goudy Bookletter 1911','value' => 'Goudy+Bookletter+1911'),
    array('label' => 'Gravitas One','value' => 'Gravitas+One'),
    array('label' => 'Gruppo','value' => 'Gruppo'),
    array('label' => 'Hammersmith One','value' => 'Hammersmith+One'),
    array('label' => 'Herr Von Muellerhoff','value' => 'Herr+Von+Muellerhoff'),
    array('label' => 'Holtwood One SC','value' => 'Holtwood+One+SC'),
    array('label' => 'Homemade Apple','value' => 'Homemade+Apple'),
    array('label' => 'IM Fell DW Pica SC','value' => 'IM+Fell+DW+Pica+SC'),
    array('label' => 'IM Fell DW Pica','value' => 'IM+Fell+DW+Pica'),
    array('label' => 'IM Fell Double Pica SC','value' => 'IM+Fell+Double+Pica+SC'),
    array('label' => 'IM Fell Double Pica','value' => 'IM+Fell+Double+Pica'),
    array('label' => 'IM Fell English SC','value' => 'IM+Fell+English+SC'),
    array('label' => 'IM Fell English','value' => 'IM+Fell+English'),
    array('label' => 'IM Fell French Canon SC','value' => 'IM+Fell+French+Canon+SC'),
    array('label' => 'IM Fell French Canon','value' => 'IM+Fell+French+Canon'),
    array('label' => 'IM Fell Great Primer SC','value' => 'IM+Fell+Great+Primer+SC'),
    array('label' => 'IM Fell Great Primer','value' => 'IM+Fell+Great+Primer'),
    array('label' => 'Iceland','value' => 'Iceland'),
    array('label' => 'Inconsolata','value' => 'Inconsolata'),
    array('label' => 'Indie Flower','value' => 'Indie+Flower'),
    array('label' => 'Irish Grover','value' => 'Irish+Grover'),
    array('label' => 'Istok Web','value' => 'Istok+Web'),
    array('label' => 'Jockey One','value' => 'Jockey+One'),
    array('label' => 'Josefin Sans','value' => 'Josefin+Sans'),
    array('label' => 'Josefin Slab','value' => 'Josefin+Slab'),
    array('label' => 'Judson','value' => 'Judson'),
    array('label' => 'Julee','value' => 'Julee'),
    array('label' => 'Jura','value' => 'Jura'),
    array('label' => 'Just Another Hand','value' => 'Just+Another+Hand'),
    array('label' => 'Just Me Again Down Here','value' => 'Just+Me+Again+Down+Here'),
    array('label' => 'Kameron','value' => 'Kameron'),
    array('label' => 'Kelly Slab','value' => 'Kelly+Slab'),
    array('label' => 'Kenia','value' => 'Kenia'),
    array('label' => 'Knewave','value' => 'Knewave'),
    array('label' => 'Kranky','value' => 'Kranky'),
    array('label' => 'Kreon','value' => 'Kreon'),
    array('label' => 'Kristi','value' => 'Kristi'),
    array('label' => 'La Belle Aurore','value' => 'La+Belle+Aurore'),
    array('label' => 'Lancelot','value' => 'Lancelot'),
    array('label' => 'Lato','value' => 'Lato'),
    array('label' => 'League Script','value' => 'League+Script'),
    array('label' => 'Leckerli One','value' => 'Leckerli+One'),
    array('label' => 'Lekton','value' => 'Lekton'),
    array('label' => 'Lemon','value' => 'Lemon'),
    array('label' => 'Limelight','value' => 'Limelight'),
    array('label' => 'Linden Hill', 'value' => 'Linden+Hill'),
    array('label' => 'Lobster Two','value' => 'Lobster+Two'),
    array('label' => 'Lobster','value' => 'Lobster'),
    array('label' => 'Lora','value' => 'Lora'),
    array('label' => 'Love Ya Like A Sister','value' => 'Love+Ya+Like+A+Sister'),
    array('label' => 'Loved by the King','value' => 'Loved+by+the+King'),
    array('label' => 'Luckiest Guy','value' => 'Luckiest+Guy'),
    array('label' => 'Maiden Orange','value' => 'Maiden+Orange'),
    array('label' => 'Mako','value' => 'Mako'),
    array('label' => 'Marck Script','value' => 'Marck+Script'),
    array('label' => 'Marvel','value' => 'Marvel'),
    array('label' => 'Mate SC','value' => 'Mate+SC'),
    array('label' => 'Mate','value' => 'Mate'),
    array('label' => 'Maven Pro','value' => 'Maven+Pro'),
    array('label' => 'Meddon','value' => 'Meddon'),
    array('label' => 'MedievalSharp','value' => 'MedievalSharp'),
    array('label' => 'Megrim','value' => 'Megrim'),
    array('label' => 'Merienda One','value' => 'Merienda+One'),
    array('label' => 'Merriweather','value' => 'Merriweather'),
    array('label' => 'Metrophobic','value' => 'Metrophobic'),
    array('label' => 'Michroma','value' => 'Michroma'),
    array('label' => 'Miltonian Tattoo','value' => 'Miltonian+Tattoo'),
    array('label' => 'Miltonian','value' => 'Miltonian'),
    array('label' => 'Miss Fajardose','value' => 'Miss+Fajardose'),
    array('label' => 'Miss Saint Delafield','value' => 'Miss+Saint+Delafield'),
    array('label' => 'Modern Antiqua','value' => 'Modern+Antiqua'),
    array('label' => 'Molengo','value' => 'Molengo'),
    array('label' => 'Monofett','value' => 'Monofett'),
    array('label' => 'Monoton','value' => 'Monoton'),
    array('label' => 'Monsieur La Doulaise','value' => 'Monsieur+La+Doulaise'),
    array('label' => 'Montez','value' => 'Montez'),
    array('label' => 'Mountains of Christmas','value' => 'Mountains+of+Christmas'),
    array('label' => 'Mr Bedford','value' => 'Mr+Bedford'),
    array('label' => 'Mr Dafoe','value' => 'Mr+Dafoe'),
    array('label' => 'Mr De Haviland','value' => 'Mr+De+Haviland'),
    array('label' => 'Mrs Sheppards','value' => 'Mrs+Sheppards'),
    array('label' => 'Muli','value' => 'Muli'),
    array('label' => 'Neucha','value' => 'Neucha'),
    array('label' => 'Neuton','value' => 'Neuton'),
    array('label' => 'News Cycle','value' => 'News+Cycle'),
    array('label' => 'Niconne','value' => 'Niconne'),
    array('label' => 'Nixie One','value' => 'Nixie+One'),
    array('label' => 'Nobile','value' => 'Nobile'),
    array('label' => 'Nosifer Caps','value' => 'Nosifer+Caps'),
    array('label' => 'Nothing You Could Do','value' => 'Nothing+You+Could+Do'),
    array('label' => 'Nova Cut','value' => 'Nova+Cut'),
    array('label' => 'Nova Flat','value' => 'Nova+Flat'),
    array('label' => 'Nova Mono','value' => 'Nova+Mono'),
    array('label' => 'Nova Oval','value' => 'Nova+Oval'),
    array('label' => 'Nova Round','value' => 'Nova+Round'),
    array('label' => 'Nova Script','value' => 'Nova+Script'),
    array('label' => 'Nova Slim','value' => 'Nova+Slim'),
    array('label' => 'Nova Square','value' => 'Nova+Square'),
    array('label' => 'Numans','value' => 'Numans'),
    array('label' => 'Nunito','value' => 'Nunito'),
    array('label' => 'Old Standard TT','value' => 'Old+Standard+TT'),
    array('label' => 'Open Sans Condensed','value' => 'Open+Sans+Condensed'),
    array('label' => 'Open Sans','value' => 'Open+Sans'),
    array('label' => 'Orbitron','value' => 'Orbitron'),
    array('label' => 'Oswald','value' => 'Oswald'),
    array('label' => 'Over the Rainbow','value' => 'Over+the+Rainbow'),
    array('label' => 'Ovo','value' => 'Ovo'),
    array('label' => 'PT Sans Caption','value' => 'PT+Sans+Caption'),
    array('label' => 'PT Sans Narrow','value' => 'PT+Sans+Narrow'),
    array('label' => 'PT Sans','value' => 'PT+Sans'),
    array('label' => 'PT Serif Caption','value' => 'PT+Serif+Caption'),
    array('label' => 'PT Serif','value' => 'PT+Serif'),
    array('label' => 'Pacifico','value' => 'Pacifico'),
    array('label' => 'Passero One','value' => 'Passero+One'),
    array('label' => 'Patrick Hand','value' => 'Patrick+Hand'),
    array('label' => 'Paytone One','value' => 'Paytone+One'),
    array('label' => 'Permanent Marker','value' => 'Permanent+Marker'),
    array('label' => 'Petrona','value' => 'Petrona'),
    array('label' => 'Philosopher','value' => 'Philosopher'),
    array('label' => 'Piedra','value' => 'Piedra'),
    array('label' => 'Pinyon Script','value' => 'Pinyon+Script'),
    array('label' => 'Play','value' => 'Play'),
    array('label' => 'Playfair Display','value' => 'Playfair+Display'),
    array('label' => 'Podkova','value' => 'Podkova'),
    array('label' => 'Poller One','value' => 'Poller+One'),
    array('label' => 'Poly','value' => 'Poly'),
    array('label' => 'Pompiere','value' => 'Pompiere'),
    array('label' => 'Prata','value' => 'Prata'),
    array('label' => 'Prociono','value' => 'Prociono'),
    array('label' => 'Puritan','value' => 'Puritan'),
    array('label' => 'Quattrocento Sans','value' => 'Quattrocento+Sans'),
    array('label' => 'Quattrocento','value' => 'Quattrocento'),
    array('label' => 'Questrial','value' => 'Questrial'),
    array('label' => 'Quicksand','value' => 'Quicksand'),
    array('label' => 'Radley','value' => 'Radley'),
    array('label' => 'Raleway','value' => 'Raleway'),
    array('label' => 'Rammetto One','value' => 'Rammetto+One'),
    array('label' => 'Rancho','value' => 'Rancho'),
    array('label' => 'Rationale','value' => 'Rationale'),
    array('label' => 'Redressed','value' => 'Redressed'),
    array('label' => 'Reenie Beanie','value' => 'Reenie+Beanie'),
    array('label' => 'Ribeye Marrow','value' => 'Ribeye+Marrow'),
    array('label' => 'Ribeye','value' => 'Ribeye'),
    array('label' => 'Righteous','value' => 'Righteous'),
    array('label' => 'Rochester','value' => 'Rochester'),
    array('label' => 'Rock Salt','value' => 'Rock+Salt'),
    array('label' => 'Rokkitt','value' => 'Rokkitt'),
    array('label' => 'Rosario','value' => 'Rosario'),
    array('label' => 'Ruslan Display','value' => 'Ruslan+Display'),
    array('label' => 'Salsa','value' => 'Salsa'),
    array('label' => 'Sancreek','value' => 'Sancreek'),
    array('label' => 'Sansita One','value' => 'Sansita+One'),
    array('label' => 'Satisfy','value' => 'Satisfy'),
    array('label' => 'Schoolbell','value' => 'Schoolbell'),
    array('label' => 'Shadows Into Light','value' => 'Shadows+Into+Light'),
    array('label' => 'Shanti','value' => 'Shanti'),
    array('label' => 'Short Stack','value' => 'Short+Stack'),
    array('label' => 'Sigmar One','value' => 'Sigmar+One'),
    array('label' => 'Signika Negative','value' => 'Signika+Negative'),
    array('label' => 'Signika','value' => 'Signika'),
    array('label' => 'Six Caps','value' => 'Six+Caps'),
    array('label' => 'Slackey','value' => 'Slackey'),
    array('label' => 'Smokum','value' => 'Smokum'),
    array('label' => 'Smythe','value' => 'Smythe'),
    array('label' => 'Sniglet','value' => 'Sniglet'),
    array('label' => 'Snippet','value' => 'Snippet'),
    array('label' => 'Sorts Mill Goudy','value' => 'Sorts+Mill+Goudy'),
    array('label' => 'Special Elite',/* */'value' => 'Special+Elite'),
    array('label' => 'Spinnaker','value' => 'Spinnaker'),
    array('label' => 'Spirax','value' => 'Spirax'),
    array('label' => 'Stardos Stencil',/* */'value' => 'Stardos+Stencil'),
    array('label' => 'Sue Ellen Francisco',/* */'value' => 'Sue+Ellen+Francisco'),
    array('label' => 'Sunshiney','value' => 'Sunshiney'),
    array('label' => 'Supermercado One','value' => 'Supermercado+One'),
    array('label' => 'Swanky and Moo Moo','value' => 'Swanky+and+Moo+Moo'),
    array('label' => 'Syncopate','value' => 'Syncopate'),
    array('label' => 'Tangerine','value' => 'Tangerine'),
    array('label' => 'Tenor Sans','value' => 'Tenor+Sans'),
    array('label' => 'Terminal Dosis','value' => 'Terminal+Dosis'),
    array('label' => 'The Girl Next Door','value' => 'The+Girl+Next+Door'),
    array('label' => 'Tienne','value' => 'Tienne'),
    array('label' => 'Tinos','value' => 'Tinos'),
    array('label' => 'Tulpen One','value' => 'Tulpen+One'),
    array('label' => 'Ubuntu Condensed','value' => 'Ubuntu+Condensed'),
    array('label' => 'Ubuntu Mono','value' => 'Ubuntu+Mono'),
    array('label' => 'Ubuntu','value' => 'Ubuntu'),
    array('label' => 'Ultra','value' => 'Ultra'),
    array('label' => 'UnifrakturCook','value' => 'UnifrakturCook'),
    array('label' => 'UnifrakturMaguntia','value' => 'UnifrakturMaguntia'),
    array('label' => 'Unkempt','value' => 'Unkempt'),
    array('label' => 'Unlock','value' => 'Unlock'),
    array('label' => 'Unna','value' => 'Unna'),
    array('label' => 'VT323','value' => 'VT323'),
    array('label' => 'Varela Round','value' => 'Varela+Round'),
    array('label' => 'Varela','value' => 'Varela'),
    array('label' => 'Vast Shadow','value' => 'Vast+Shadow'),
    array('label' => 'Vibur','value' => 'Vibur'),
    array('label' => 'Vidaloka','value' => 'Vidaloka'),
    array('label' => 'Volkhov','value' => 'Volkhov'),
    array('label' => 'Vollkorn','value' => 'Vollkorn'),
    array('label' => 'Voltaire','value' => 'Voltaire'),
    array('label' => 'Waiting for the Sunrise','value' => 'Waiting+for+the+Sunrise'),
    array('label' => 'Wallpoet','value' => 'Wallpoet'),
    array('label' => 'Walter Turncoat','value' => 'Walter+Turncoat'),
    array('label' => 'Wire One','value' => 'Wire+One'),
    array('label' => 'Yanone Kaffeesatz','value' => 'Yanone+Kaffeesatz'),
    array('label' => 'Yellowtail','value' => 'Yellowtail'),
    array('label' => 'Yeseva One','value' => 'Yeseva+One'),
    array('label' => 'Zeyada','value' => 'Zeyada')
);

/**
 * Initialize the options before anything else. 
 */
add_action('admin_init', 'ss_theme_options');

/**
 * Theme Mode demo code of all the available option types.
 *
 * @return    void
 *
 * @access    private
 * @since     2.0
 */
function ss_theme_options() {
    /**
     * All available pages chosen for portfolio page.
     */
    global $pages_array;

    /**
     * Slider Animation Effects Options.
     */
    global $slider_effects;

    /**
     * Slider Animation Speeds Options.
     */
    global $slider_speeds;

    /**
     * Google Fonts Options.
     */
    global $google_fonts;

    /**
     * Get a copy of the saved settings array. 
     */
    $saved_settings = get_option( 'option_tree_settings', array() );
    
    /**
     * Create a custom settings array that we pass to 
     * the OptionTree Settings API Class.
     */
    $custom_settings = array(
        'contextual_help'     => array(
            'content'         => array( 
                array(
                    'id'      => 'general_help',
                    'title'   => 'General',
                    'content' => '<p>Help content goes here!</p>',
                )
            ),
            'sidebar'         => '<p>Sidebar content goes here!</p>',
        ),
        'sections'            => array(
            array(
                'id'          => 'general',
                'title'       => 'General',
            ),
            array(
                'id'          => 'slider',
                'title'       => 'Slider',
            ),
            array(
                'id'          => 'header',
                'title'       => 'Header',
            ), 
            array(
                'id'          => 'footer',
                'title'       => 'Footer',
            ),
            array(
                'id'          => 'portfolio',
                'title'       => 'Portfolio',
            ),
            array(
                'id'          => 'typo',
                'title'       => 'Typography',
            ),
        ),
        'settings'            => array(
            /* General Settings */
            array(
                'label'       => __('Upgrade Broswer URL', TPLNAME),
                'id'          => TPLNAME . '_upgrade_browser_url',
                'type'        => 'text',
                'desc'        => __('The url of page noticing users to upgrade their broswers.', TPLNAME),
                'std'         => '/not-supported',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ), 
            array(
                'label'       => __('CDN Base URL', TPLNAME),
                'id'          => TPLNAME . '_cdn_base_url',
                'type'        => 'text',
                'desc'        => __('The base url of CDN service.', TPLNAME),
                'std'         => LGR_BASE_URL,
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ), 
            array(
                'label'       => __('Blog layout', TPLNAME),
                'id'          => TPLNAME . '_blog_layout',
                'type'        => 'radio-image',
                'desc'        => __('Choose sidebar side on blog.', TPLNAME),
                'std'         => 'right-sidebar',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ), 
            array(
                'label'       => __('Blog posts icons', TPLNAME),
                'id'          => TPLNAME . '_blog_icons',
                'type'        => 'select',
                'desc'        => __('Enable/disable "post types" icons', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => __('Enable', TPLNAME),
                        'value'       => 'enable',
                    ),
                    array(
                        'label'       => __('Disable', TPLNAME),
                        'value'       => 'disable',
                    )
                ),
                'std'         => 'enable',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ), 
            array(
                'label'       => __('Blog content excerpt length', TPLNAME),
                'id'          => TPLNAME . '_excerpt_length',
                'type'        => 'text',
                'desc'        => __('The max length to display in blog page for each post', TPLNAME),
                'std'         => '100',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ),
            array(
                'id'          => TPLNAME . '_custom_css',
                'label'       => __('Custom CSS', TPLNAME),
                'desc'        => __('To prevent problems with theme update, write here any custom css (or use child themes)', TPLNAME),
                'std'         => '',
                'type'        => 'textarea-simple',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ),
            array(
                'id'          => TPLNAME . '_analytics_code',
                'label'       => __('Analytics code', TPLNAME),
                'desc'        => __('Put here your  Analytics script code', TPLNAME),
                'std'         => '',
                'type'        => 'textarea-simple',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'general',
            ),
            /* Slider Settings */
            array(
                'label'       => __('Enable slider', TPLNAME),
                'id'          => TPLNAME . '_slider_on',
                'type'        => 'select',
                'desc'        => __('Show slider on homepage', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => __('Yes', TPLNAME),
                        'value'       => 'yes',
                    ),
                    array(
                        'label'       => __('No', TPLNAME),
                        'value'       => 'no',
                    )
                ),
                'std'         => 'yes',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'slider',
            ),
            array(
                'label'       => __('Select slider for homepage', TPLNAME),
                'id'          => TPLNAME . '_slider_home',
                'type'        => 'select',
                'desc'        => __('Select slider for homepage', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => __('Flex Slider', TPLNAME),
                        'value'       => 'flex',
                    ),
                    array(
                        'label'       => __('Revolution Slider', TPLNAME),
                        'value'       => 'revolution',
                    )
                ),
                'std'         => 'yes',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'slider',
            ),
            array(
                'id'          => TPLNAME . '_slider_text',
                'label'       => __('About Slider', TPLNAME),
                'desc'        => __('Below you can create slides for Flexslider.', TPLNAME),
                'std'         => '',
                'type'        => 'textblock',
                'section'     => 'slider',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
            ),
            array(
                'label'       => __('Homepage Flexslider', TPLNAME),
                'id'          => TPLNAME . '_mainslider',
                'type'        => 'list-item',
                'desc'        => __('Add slides for homepage slider.', TPLNAME),
                'settings'    => array(
                    array(
                        'label'       => __('Extenal link of slide', TPLNAME),
                        'id'          => TPLNAME . '_slide_extenal_link',
                        'type'        => 'text',
                        'desc'        => __('The extenal link of the slide', TPLNAME),
                        'std'         => '',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'class'       => '',
                    ),
                    array(
                        'label'       => __('Content of slide', TPLNAME),
                        'id'          => TPLNAME . '_slide_description',
                        'type'        => 'textarea',
                        'desc'        => __('You can use shortcodes here.', TPLNAME),
                        'std'         => '',
                        'rows'        => '10',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'class'       => '',
                    ),
                    array(
                        'label'       => __('Upload Image', TPLNAME),
                        'id'          => TPLNAME . '_slide_image_upload',
                        'type'        => 'upload',
                        'desc'        => __('Upload image for slide' , TPLNAME),
                        'std'         => '',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'class'       => '',
                    )
                ),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'slider',
            ),
            /* Header Settings */
            array(
                'label'       => __('Upload logo', TPLNAME),
                'id'          => TPLNAME . '_logo_upload',
                'type'        => 'upload',
                'desc'        => __('For best effect logo image should be transparent png, logo from live preview has 114x24px but you can use bigger, you will probably need to adjust some margins using options below ', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            array(
                'label'       => __('Logo area width', TPLNAME),
                'id'          => TPLNAME . '_logo_area_width',
                'type'        => 'select',
                'desc'        => __('Full width of top area is 12 columns. Logo area by default is 4 columns, while navigation is 8 columns wide. If you want to have bigger logo, please change here number of columns for logo. ', TPLNAME),
                'choices'     => array(
                    array('label'  => '1 column',  'value' => '1'),
                    array('label'  => '2 columns', 'value' => '2'),
                    array('label'  => '3 columns', 'value' => '3'),
                    array('label'  => '4 columns', 'value' => '4'),
                    array('label'  => '5 columns', 'value' => '5'),
                    array('label'  => '6 columns', 'value' => '6'),
                    array('label'  => '7 columns', 'value' => '7'),
                    array('label'  => '8 columns', 'value' => '8'),
                    array('label'  => '9 columns', 'value' => '9'),
                    array('label'  => '10 columns','value' => '10'),
                    array('label'  => '11 columns','value' => '11'),
                    array('label'  => '12 columns','value' => '12'),
                ),
                'std'         => '4',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            array(
                'label'       => __('Logo top margin', TPLNAME),
                'id'          => TPLNAME . '_logo_top_margin',
                'type'        => 'measurement',
                'desc'        => __('Set top margin for logo image', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            array(
                'label'       => __('Logo bottom margin', TPLNAME),
                'id'          => TPLNAME . '_logo_bottom_margin',
                'type'        => 'measurement',
                'desc'        => __('Set bottom margin for logo image', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            array(
                'label'       => __('Favicon ', TPLNAME),
                'id'          => TPLNAME . '_favicon_upload',
                'type'        => 'upload',
                'desc'        => __('Upload favicon here (16x16)', TPLNAME),
                'std'         => 'favicon.ico',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            array(
                'label'       => __('Tagline top margin', TPLNAME),
                'id'          => TPLNAME . '_tagline_margin',
                'type'        => 'measurement',
                'desc'        => __('Set top margin for tagline to position it correctly (Tagline is set in Settings -> General -> Tagline).', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'header',
            ),
            /* Footer Settings */
            array(
                'label'       => __('Footer Social Icons', TPLNAME),
                'id'          => TPLNAME . '_socialicons',
                'type'        => 'list-item',
                'desc'        => __('Manage socials icons on header.', TPLNAME),
                'settings'    => array(
                    array(
                        'id'          => TPLNAME . '_icons_service',
                        'label'       => __('Choose service', TPLNAME),
                        'desc'        => __('', TPLNAME),
                        'std'         => '',
                        'type'        => 'select',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'class'       => '',
                        'choices'     => array( 
                            array('value'=> 'behance',        'label' => 'Behance',       'src'=> ''),
                            array('value'=> 'facebook',       'label' => 'Facebook',      'src'=> ''),
                            array('value'=> 'flickr',         'label' => 'Flickr',        'src'=> ''),
                            array('value'=> 'github',         'label' => 'Github',        'src'=> ''),
                            array('value'=> 'google-plus',    'label' => 'Google+',       'src'=> ''),
                            array('value'=> 'instagram',      'label' => 'Instagram',     'src'=> ''),
                            array('value'=> 'lastfm',         'label' => 'LastFM',        'src'=> ''),
                            array('value'=> 'linkedin',       'label' => 'LinkedIn',      'src'=> ''),
                            array('value'=> 'qq',             'label' => 'QQ',            'src'=> ''),
                            array('value'=> 'skype',          'label' => 'Skype',         'src'=> ''),
                            array('value'=> 'stack-overflow', 'label' => 'StackOverflow', 'src'=> ''),
                            array('value'=> 'tumblr',         'label' => 'Tumblr',        'src'=> ''),
                            array('value'=> 'twitter',        'label' => 'Twitter',       'src'=> ''),
                            array('value'=> 'wechat',         'label' => 'Wechat',        'src'=> ''),
                            array('value'=> 'weibo',          'label' => 'Weibo',         'src'=> ''),
                            array('value'=> 'wordpress',      'label' => 'WordPress',     'src'=> ''),
                            array('value'=> 'yahoo',          'label' => 'Yahoo',         'src'=> ''),
                            array('value'=> 'youtube',        'label' => 'YouTube',       'src'=> ''),
                        ),
                    ),
                    array(
                        'label'       => __('URL to profile page', TPLNAME),
                        'id'          => TPLNAME . '_icons_url',
                        'type'        => 'text',
                        'desc'        => __('', TPLNAME),
                        'std'         => '',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'class'       => '',
                    )
                ),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'footer',
            ),
            array(
                'label'       => __('Contact detail address', TPLNAME),
                'id'          => TPLNAME . '_cdetail_address',
                'type'        => 'text',
                'desc'        => __('Your contact address', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'footer',
            ),
            array(
                'label'       => __('Contact detail email', TPLNAME),
                'id'          => TPLNAME . '_cdetail_email',
                'type'        => 'text',
                'desc'        => __('Your contact email', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'footer',
            ),
            array(
                'label'       => __('Contact detail phone', TPLNAME),
                'id'          => TPLNAME . '_cdetail_phone',
                'type'        => 'text',
                'desc'        => __('Your contact phone', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'footer',
            ),
            array(
                'label'       => __('Copyright', TPLNAME),
                'id'          => TPLNAME . '_copyright',
                'type'        => 'text',
                'desc'        => __('Copyright text in footer', TPLNAME),
                'std'         => 'Copyright&copy; 2005-${year} <a href="http://zjhzxhz.com">Infinite Script</a>. All rights reserved.',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'footer',
            ),
            /* Portfolio Settings */
            array(
                'label'       => __('Portfolio page', TPLNAME),
                'id'          => TPLNAME . '_portfolio_page',
                'type'        => 'select',
                'desc'        => __('Select the portfolio page to fix any navigation issues (correct highlighting etc.).', TPLNAME),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
                'choices'     => $pages_array,
            ),
            array(
                'label'       => __('Portfolio columns layout', TPLNAME),
                'id'          => TPLNAME . '_portfolio_layout',
                'type'        => 'select',
                'desc'        => __('Choose number of columns for portfolio archive page', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => '2 columns',
                        'value'       => '2',
                    ),
                    array(
                        'label'       => '3 columns',
                        'value'       => '3',
                    ),
                    array(
                        'label'       => '4 columns',
                        'value'       => '4',
                    ),
                    array(
                        'label'       => '6 columns',
                        'value'       => '6',
                    )
                ),
                'std'         => '3',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
            ),
            array(
                'label'       => __('Portfolio rewrite slug', TPLNAME),
                'id'          => TPLNAME . '_portfolio_slug',
                'type'        => 'text',
                'desc'        => __('The slug in URL for portfolio page. You need to update Permalink Settings to make it work', TPLNAME),
                'std'         => 'portfolio-item',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
            ),
            array(
                'label'       => __('Enable lightbox in single project page', TPLNAME),
                'id'          => TPLNAME . '_single_project_lightbox',
                'type'        => 'select',
                'desc'        => __('This setting will determine can thumbnails be zoomed in single project page.', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => __('Yes', TPLNAME),
                        'value'       => 'yes',
                    ),
                    array(
                        'label'       => __('No', TPLNAME),
                        'value'       => 'no',
                    )
                ),
                'std'         => 'yes',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
            ),
            array(
                'label'       => __('Project Slider - Animation effect', TPLNAME),
                'id'          => TPLNAME . '_project_slider_effect',
                'type'        => 'select',
                'desc'        => __('Transition type for the animation.', TPLNAME),
                'std'         => 'fixedScrollHorz',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
                'choices'     => $slider_effects,
            ),
            array(
                'label'       => __('Project Slider - Animation speed', TPLNAME),
                'id'          => TPLNAME . '_project_slider_speed',
                'type'        => 'select',
                'desc'        => __('Speed of the animation transition', TPLNAME),
                'std'         => '600',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
                'choices'     => $slider_speeds,
            ),
            array(
                'label'       => __('Project Slider - Autoplay timeouts', TPLNAME),
                'id'          => TPLNAME . '_project_slider_timeout',
                'type'        => 'text',
                'desc'        => __('Time between slide transitions. Value is in milliseconds (0 for disable autoplay)', TPLNAME),
                'std'         => '0',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'portfolio',
            ),
            /* Typography Settings */
            array(
                'label'       => __('Enable custom fonts', TPLNAME),
                'id'          => TPLNAME . '_fonts_on',
                'type'        => 'select',
                'desc'        => __('Note that this is experimental feature, not all fonts might work properly.', TPLNAME),
                'choices'     => array(
                    array(
                        'label'       => __('No', TPLNAME),
                        'value'       => 'no',
                    ),
                    array(
                        'label'       => __('Yes', TPLNAME),
                        'value'       => 'yes',
                    )
                ),
                'std'         => 'no',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'typo',
            ),
            array(
                'label'       => __('Body font', TPLNAME),
                'id'          => TPLNAME . '_body_font',
                'desc'        => __('Choose font for body (We recommend Open Sans).', TPLNAME),
                'std'         => '',
                'type'        => 'select',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => '',
                'section'     => 'typo',
                'choices'     => $google_fonts,
            ),
        ),
    );

    /* settings are not the same update the DB */
    if ( $saved_settings !== $custom_settings ) {
        update_option( 'option_tree_settings', $custom_settings ); 
    }
}